[package]
name = "rust_performance_demo"
version = "0.1.0"
edition = "2024"

[dev-dependencies]
criterion = "0.5.1"

[[bench]]
name = "disemvowel_benchmark"
harness = false

[[bench]]
name = "db_operations"
harness = false
